### ISSUE TITLE
Is it possible to keep multiple versions for your salt brew formula?

### ISSUE THREAD

**Issue by mariusmaneaorg** [cdalvaro/homebrew-tap#41]
Hey there,

First off, thanks for your work so far!

Is it possible to maintain multiple versions of your salt formula?
You currently updated salt to 3003, but I'd like to use 3002.6
Do you know how I can do that?

thanks a lot,
Marius

**Comment by cdalvaro** [comment]
Hi! Thank you for your issue!

I'll add versioned salt formula for version `3002.6`

**Comment by mariusmaneaorg** [comment]
Awesome, thanks a lot!
